const ROUNDS=[
  {type:'cookies',animal:'cookie',label:'小饼干',count:7,options:[4,6,7],intro:['烤箱里需要放置 7 个面团。','你来试试吧！']},
  {type:'cats',animal:'cat',label:'小猫',count:9,options:[9,6],intro:['澡堂里有好多猫咪啊。','是几只呢？','你来数一数。']},
  {type:'crabs',animal:'crab',label:'小螃蟹',count:4,intro:['海洋里有好多小螃蟹啊。','有几只？','你伸出小手来点一点。']}
];
const state={roundIndex:0,counted:0,speaking:false,voice:true,mood:'question',dialogue:'',sequenceId:0};
const audioCache=new Map();const voiceAudio=document.querySelector('#voiceAudio');let voiceUnlocked=false;
const animationSources={question:'assets/mitu-doubt.gif',counting:'assets/mitu-speaking.gif',celebrate:'assets/mitu-happy.gif',encourage:'assets/mitu-wrong.gif',idle:'assets/mitu-idle.gif'};
const choicesEl=document.querySelector('#choices'),progressFill=document.querySelector('#progressFill'),dialogueText=document.querySelector('#dialogueText'),panel=document.querySelector('#dialoguePanel'),sprite=document.querySelector('#mituSprite'),mituWrap=document.querySelector('.mitu-wrap'),resultEl=document.querySelector('#countResult'),nextRoundBtn=document.querySelector('#nextRoundBtn'),promptNumber=document.querySelector('#promptNumber');
const round=()=>ROUNDS[state.roundIndex];
function introLines(){return round().intro}
function updateProgress(){const value=(state.roundIndex+state.counted/round().count)/ROUNDS.length*100;progressFill.style.width=`${value}%`}
 function renderRound(){setMood('idle');choicesEl.innerHTML='';choicesEl.className=`choices ${round().type}`;choicesEl.classList.remove('complete');resultEl.hidden=true;nextRoundBtn.hidden=true;state.counted=0;updateProgress();promptNumber.hidden=round().type!=='cookies';promptNumber.textContent=round().type==='cookies'?round().count:'';if(round().options){if(round().type==='cats')choicesEl.innerHTML=`<div class="cat-bath" aria-label="9只小猫"><span class="cat-group">${Array.from({length:round().count},()=>'<span class="cat-face">🐱</span>').join('')}</span></div>`;round().options.forEach(value=>{const card=document.createElement('button');card.className='answer-card';const content=round().type==='cats'?`<strong class="answer-number">${value}</strong>`:`<span class="answer-icon ${round().animal}">${Array.from({length:value},()=>'<i class="cookie-dot"></i>').join('')}</span>`;card.innerHTML=content;card.setAttribute('aria-label',`${value}个${round().label}`);card.addEventListener('click',()=>answerRound(value,card));choicesEl.appendChild(card)})}else{const spots=[[7,5],[60,9],[20,45],[68,52],[43,25]].sort(()=>Math.random()-.5);spots.slice(0,round().count).forEach((spot,index)=>{const creature=document.createElement('button');creature.className='choice';creature.style.left=`${spot[0]}%`;creature.style.top=`${spot[1]}%`;creature.style.setProperty('--final-left',`${50-(round().count-1)*8+index*16}%`);creature.innerHTML=`<span class="crab crab"><i></i><i></i><em></em></span>`;creature.addEventListener('click',()=>countCreature(creature),{once:true});choicesEl.appendChild(creature)})}}
function setMood(mood){state.mood=mood;sprite.className=`mitu-sprite ${mood}`;sprite.src=animationSources[mood]||animationSources.question}
async function playRemoteVoice(text){if(!state.voice||!voiceUnlocked)return;try{let url=audioCache.get(text);if(!url){const response=await fetch('https://tts.mathufo.com/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:[text],voice_name:'zh_male_tiancaitongsheng_mars_bigtts'})});if(!response.ok)throw new Error('tts request failed');const payload=await response.json();const file=payload?.data?.[0];if(!file)throw new Error('missing audio file');url=`https://cdn.mathufo.com/sound/${file}`;audioCache.set(text,url)}voiceAudio.src=url;voiceAudio.currentTime=0;const started=await voiceAudio.play().then(()=>true,()=>false);if(!started)throw new Error('audio playback blocked');await new Promise(resolve=>{voiceAudio.onended=resolve;voiceAudio.onerror=resolve})}catch{if('speechSynthesis'in window){await new Promise(resolve=>{speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(text);utter.lang='zh-CN';utter.rate=.95;utter.onend=resolve;utter.onerror=resolve;speechSynthesis.speak(utter)})}}}
function wakeDialogue(){clearTimeout(state.idleTimer);panel.classList.remove('idle');panel.classList.add('awake')}
function idleDialogue(){clearTimeout(state.idleTimer);state.idleTimer=setTimeout(()=>{panel.classList.remove('awake');panel.classList.add('idle');setMood('idle')},900)}
function speak(text){wakeDialogue();if(/不对|再试一次|不是/.test(text))setMood('encourage');else if(/[?？吗呢哪]/.test(text))setMood('question');else setMood('counting');state.dialogue=text;state.speaking=true;panel.classList.add('speaking');dialogueText.textContent='';let i=0;let displayDone;const displayPromise=new Promise(resolve=>{displayDone=resolve});clearInterval(speak.timer);speak.timer=setInterval(()=>{dialogueText.textContent=text.slice(0,++i);if(i>=text.length){clearInterval(speak.timer);state.speaking=false;panel.classList.remove('speaking');displayDone()}},34);let playback=Promise.resolve();if(state.voice&&voiceUnlocked){if('speechSynthesis'in window)speechSynthesis.cancel();voiceAudio.pause();playback=playRemoteVoice(text)}return Promise.all([playback,displayPromise]).finally(idleDialogue)}
async function speakSequence(lines,onLine,onComplete){const id=++state.sequenceId;for(let index=0;index<lines.length;index++){if(id!==state.sequenceId)return;onLine?.(index);await speak(lines[index]);if(index<lines.length-1)await new Promise(resolve=>setTimeout(resolve,180))}if(id===state.sequenceId)onComplete?.()}
function showResult(){if(round().type!=='crabs')return;resultEl.querySelector('span').textContent=round().count;resultEl.querySelector('p').textContent=`一共有 ${round().count} 只`;resultEl.hidden=false}
function answerRound(value,card){if(value===round().count){card.classList.add('correct');card.setAttribute('aria-label','回答正确');state.counted=round().count;updateProgress();finishRound()}else{card.classList.add('wrong');card.setAttribute('aria-label','回答错误，请再试一次');setMood('encourage');const retryText=round().type==='cookies'?'不对哦，这个不是 7，你再找找看。':'再试一次，数一数哪个选项是正确的。';speak(retryText);setTimeout(()=>card.classList.remove('wrong'),1200)}}
function finishRound(){[...choicesEl.children].forEach(item=>item.disabled=true);choicesEl.classList.add('complete');setMood('celebrate');if(round().type==='cookies'){speak('你答对啦，这个就是 7');nextRoundBtn.hidden=false;return}const count=String(round().count);speakSequence([count,`一共有${count}只。`,`我们可以用数字${count}表示。`],index=>{if(index===1)showResult()},()=>{nextRoundBtn.hidden=false})}
function countCreature(creature){if(creature.classList.contains('counted'))return;creature.classList.add('counted');state.counted++;updateProgress();if(state.counted<round().count){setMood('counting');speak(String(state.counted))}else finishRound()}
function nextRound(){if(state.roundIndex<ROUNDS.length-1){state.roundIndex++;renderRound();setMood('question');speakSequence(introLines())}else{nextRoundBtn.hidden=true;setMood('celebrate');speak('你完成所有海洋数数题啦！')}}
function finishImmediately(){state.counted=round().count;[...choicesEl.children].forEach(item=>{item.disabled=true;item.classList.add('counted')});updateProgress();finishRound()}
function restart(){state.roundIndex=0;state.sequenceId++;renderRound();setMood('question');speakSequence(introLines())}
function unlockVoice(){voiceUnlocked=true;document.removeEventListener('pointerdown',unlockVoice);speak(state.dialogue)}document.addEventListener('pointerdown',unlockVoice);mituWrap.onclick=()=>{if(panel.classList.contains('idle')){setMood('question');speak('我在这里，和我一起数一数吧。')}};document.querySelector('#collapseBtn').onclick=()=>{panel.hidden=true;document.querySelector('#expandBtn').hidden=false};document.querySelector('#expandBtn').onclick=()=>{panel.hidden=false;document.querySelector('#expandBtn').hidden=true};document.querySelector('#skipBtn').onclick=finishImmediately;document.querySelector('#homeBtn').onclick=restart;nextRoundBtn.onclick=nextRound;renderRound();setMood('question');speakSequence(introLines());
